stores:
    - store: estuary-alex-testing
      credentials:
        credentials_title: Private App Credentials
        access_token_sops: ENC[AES256_GCM,data:U4H9/+mC+YbmCzSeQOs77ikDHAFAl8flLkohlfLvIG4oR6O444s=,iv:RpboQbPOJnctlQeH2EEnns+xtBydFpD6TecqLiilFD4=,tag:zWOk5wMGZObyaLemX0bZ7w==,type:str]
start_date: "2025-01-10T00:00:00Z"
advanced:
    window_size: P50000D
sops:
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2026-02-10T14:31:14Z"
          enc: CiQAdmEdwsIlJneQ2fXL155ChSwlJWjSsbXJPov0rLvZ67BYKaISSQDNZIk6KsWXDUNAXjyc2C/5rNbt67SyOZRv+8m0bkmtWcHAkq7Qe2CdsqquG2FG5Mc0XPVvt7wmhb1N51XpxaGykrD79QbhWR4=
    lastmodified: "2026-02-10T14:31:14Z"
    mac: ENC[AES256_GCM,data:/pYcG5z75ME8I68UVj1whiJAHRTp/VOAoAa0elRQiPJCP93LvAFeNhekN4T23pdyiscL88prwVNjzS8dMvAPSTSxF0T/H2di7BYqDawAEKV4C42cup74wB1Gxl8QeUpTwmYIlOSq/13kuSF+mEruPrTvvnSddiwkYrGyUciEPJo=,iv:R2u0T3Nrsqbuin5HE9xkk9mlOXCOJEo6NVmvuftv2o0=,tag:IeX6GSZ+hF7n36fEilmFfw==,type:str]
    encrypted_suffix: _sops
    version: 3.10.2
