credentials:
    credentials_title: OAuth Credentials
    client_id_sops: ENC[AES256_GCM,data:fMXpKq4TrDG9vbkRFa7EYhOsdk6FtTLLT+jU5hokrHEB2FF8h39CquHiOp0+El0Mg/4zQMTdJ5wDp90WKSPa9yxzaMAi97ExkqfNWPM2FNAK2KmAYg==,iv:8lNVaJITypPnTuUZM4kMXUMdJglGFdkDYGNGhyPsxVU=,tag:yT1ENGiQzGZKM8DCT8gS0g==,type:str]
    client_secret_sops: ENC[AES256_GCM,data:jJgwo0E280bY9JApzBDCXuFaEbnnMMhtT0zYrwybJcOtZc+6RXNkxtQSbXvw9DpAAC6jbGEXMMc6yONx4y21ww==,iv:KqFuPgJzjVgDdOdKGRrnvEda/ZUUBvvlBjUcEdiALeg=,tag:M2RoEtnWixP86GOv/uwMIw==,type:str]
    refresh_token_sops: ENC[AES256_GCM,data:eIILYvGXEoiYFUkiINynzZD0KpHZtE9Bp1gmztE2qF/NEA21bV53GMJMliOdHGxEB1CDxL+4qPfctUcPTH32ibuAUIu6dxOUk9Kbzf+uU7yYmm9GxZlv,iv:ibZwf82Oyy3s+86izmjI8PR8r0x5G3ohUYaa7glG26A=,tag:4LDfYELUD9KzFL0Y8OUk7Q==,type:str]
    instance_url: https://estuary2-dev-ed.develop.my.salesforce.com
is_sandbox: false
start_date: "2024-07-26T00:00:00Z"
advanced:
    window_size: 1000
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-07-26T15:53:37Z"
          enc: CiQAdmEdwpmP0/Kcv6L1SnM3nPbsYLywIaUeOL1mz7cZjFUwWt0SSQD5lVw43Of1YI96anxUVo7d7ALi0DYnCNvxTHCgHX5ZeDBPlfXwLNpmYb6y3hJSsHG7NupwDQT/qIpUvlqQnq5IVkgJEFHPU1s=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-13T20:09:56Z"
    mac: ENC[AES256_GCM,data:iNZwuj2CybdBustBKyHjASgPIfYAaxjguTmaECpL+kHXcVOlDU5wXuKvXyf/8mPFQFeojhC0EuxcolGsUpx42DLCa/xgOs+e2Dn1JPaya9g6bn60E1cqIyMeGCwtVvpgqXzgQGsQDyr/MEa5dRJCx4Eo7oADoFhVqJiUWdwRnl4=,iv:jrJjYzyoQabCJIPyLP73FoKNocvt6q15TmITqHu2bbw=,tag:sydnFP4qPnlipxBJnH+Kdw==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.9.0
