version: "3.7"

services:
  db:
    image: 'icr.io/db2_community/db2'
    hostname: db2server
    privileged: true
    ports:
      - "50000:50000"
    volumes:
      - type: bind
        source: ./docker-initdb.sh
        target: /var/custom/docker-initdb.sh
    environment:
      LICENSE: "accept"
      DB2INSTANCE: "db2inst1"
      DB2INST1_PASSWORD: "gf6w6dkD"
      DBNAME: "testdb"
      BLU: "false"
      ENABLE_ORACLE_COMPATIBILITY: "false"
      UPDATEAVAIL: "NO"
      TO_CREATE_SAMPLEDB: "false"
      REPODB: "false"
      IS_OSXFS: "false"
      PERSISTENT_HOME: "true"
      HADR_ENABLED: "false"
    healthcheck:
      test: "su - db2inst1 -c 'db2 connect to testdb' || exit 1"
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    networks:
      - flow-test

networks:
  flow-test:
    name: flow-test
    external: true
