[tool.poetry]
name = "source_twilio"
version = "0.1.0"
description = ""
authors = ["Luis Salomao <luish1980@hotmail.com>"]

[tool.poetry.dependencies]
python = ">=3.11,^3.12.1"
estuary-cdk = {path="../estuary-cdk", develop = true}
airbyte-cdk = "^0.52"
pydantic = "1.10.14"
pendulum = "^3.0.0"
cryptography = "==43.0.1"

[tool.poetry.group.dev.dependencies]
debugpy = "^1.8.0"
mypy = "^1.8.0"
pytest = "^7.4.3"
pytest-insta = "^0.3.0"
requests-mock = "^1.11.0"
pytest-mock = "^3.12.0"
mock = "^5.1.0"
freezegun = "^1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"