[package]
name = "bson-transcoder"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = { version = "3.1", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-transcode = "1.1"
thiserror = "1.0"
