merchant_id: 7bsbj4jzqs733j2f
start_date: "2024-09-01T00:00:00Z"
credentials:
    credentials_title: API Key
    username_sops: ENC[AES256_GCM,data:d+uSBcQzzHLpXrS5V3YUaw==,iv:nVZCDUet+7KSzntkkAD2UUJICykpFyNhTayESOseQhY=,tag:Xnq3RFeWj+R1BZyeqq1quQ==,type:str]
    password_sops: ENC[AES256_GCM,data:9ZA97LWsl71jev6gUU/xejm62/wU+E5prjLcwahtb2c=,iv:c7biwuboJb6uMrnNHoPX5udegxpM49P4qBnupoDNmes=,tag:3i6DsY4IFC6bEfRiOtHARA==,type:str]
advanced:
    is_sandbox: true
    window_size: 1248
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-12-02T22:50:13Z"
          enc: CiQAdmEdwj+A1dBTgkht9vgIrwzjVgH3+QVZNPOHCjyXXAGHUZsSSQAAUDtkbF87TtphcoealDI8o+iX8PwUhi095Lf7HZOw793p3YFUsYReK6/kXkoTZN+V2+lQPWLO31aXvY3WOT4s2LakGs1n03E=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-11T03:25:01Z"
    mac: ENC[AES256_GCM,data:9Ufu+bgq8q1aH1LVB7EKwoRy5bzvNwTkzW/KihWb6pmHQxRuygUBuJ0y7v5qdKK7Yqc6j62LR/tO1GN5xfynL0E5/x+b4kBm1EKSyfN8BVYGx/xKMhkqXmFGMq42PSrllgHvwLhyprs+vJGRzletl4rRwrd4LFe0ytIutt26aXM=,iv:DXdFZ+DR0mKVKW0UjjLoFxezMuo/KZnQNpdJEbFlrOs=,tag:TwreZr+7IrvEY9fZJeXK8A==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.9.0
