[tool.poetry]
name = "source-zendesk-support"
version = "0.1.0"
description = ""
authors = ["Alex Bair <alexb@estuary.dev>"]

[tool.poetry.dependencies]
airbyte-cdk = "^0.52"
estuary-cdk = {path="../estuary-cdk", develop = true}
python = "^3.11"
pydantic = "< 1.10.15"
pytz = "^2024.1"
requests-futures = "^1.0.1"
urllib3 = "^2.2.4"
pycares = "^4.9.0"
requests = "^2.32.4"
Jinja2 = "^3.1.5"
aiohttp = "^3.11.11"

[tool.poetry.group.dev.dependencies]
debugpy = "^1.8.0"
mypy = "^1.8.0"
pytest = "^7.4.3"
pytest-insta = "^0.3.0"
requests-mock = "^1.11.0"
pytest-mock = "^3.12.0"
freezegun = "^1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
