credentials:
    credentials_title: API Key
    access_token_sops: ENC[AES256_GCM,data:ahq3zFIiztn/QIx/UB10KRRPJdBzvQM3CjgiVa/4977qtYIaug==,iv:urvMFErNkLbL3/ZOaw1e0sCz1Jxbkj30QCyxOtzDon8=,tag:JCn2QwJIaa4qYOlv6cysmw==,type:str]
start_date: "2025-08-12T00:00:00Z"
advanced:
    custom_event_streams:
        - name: profile_id_abc_events
          profile_id: abc
        - name: metric_id_123_events
          metric_id: "123"
        - name: profile_zyw_events
          profile: zyw
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-07-26T15:53:37Z"
          enc: CiQAdmEdwpmP0/Kcv6L1SnM3nPbsYLywIaUeOL1mz7cZjFUwWt0SSQD5lVw43Of1YI96anxUVo7d7ALi0DYnCNvxTHCgHX5ZeDBPlfXwLNpmYb6y3hJSsHG7NupwDQT/qIpUvlqQnq5IVkgJEFHPU1s=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-19T03:38:17Z"
    mac: ENC[AES256_GCM,data:8r8qrCti8UnrvdG4oNUnEhtxPJw1sE6NZTdaKFYM9darlYJPJT/ssl2Z5460dh9+uzcDblzKCIwpm9+rH1YNN6xTz1TSo78K3uiiWCqdTl0eOeDWuGb3xni6LYBa8ADW65Ev9DDyaOv7B0DVNH7N/6TtC76V+kHjdkIPEsTBs0o=,iv:HEMZHibqDz2HvpuLWl+ATdgfIovjQ91KcfoIdZTQRoI=,tag:iSdvQha1+f6pVPc862dzaw==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.9.0
